# Generated by Django 2.2.14 on 2020-11-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='post_pic/'),
        ),
    ]
