# Generated by Django 2.2.14 on 2020-11-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201112_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=300, upload_to='post_pic/', width_field=300),
        ),
    ]
