# Generated by Django 2.2.14 on 2020-11-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201112_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='post_pic/'),
        ),
    ]
